name: Tests

on:
  push:
    paths:
      - "Projects/mayfieldswap/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "Projects/mayfieldswap/**"
      - ".github/workflows/test.yml"

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Projects/mayfieldswap
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: npm install
      - name: Test
        run: npm test
